### ISSUE TITLE
Upload plain text

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#10]
Quickly sharing text would be a great feature

**Comment by dtext** [comment]
To elaborate:

There are sites like [pastebin](http://pastebin.com/) and [pastie](http://pastie.org/) (although pastie seems to have some hiccups lately) to share code (or any type of structured plain text, really).

I could also think of a function to automatically open [twitter](https://twitter.com/intent/tweet?text=Check%20out%20instantshare!%20https://github.com/instantshare/instantshare/) or [facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2Finstantshare%2Finstantshare%2F) with the contents of the clipboard pre-typed (click those links for an example). For twitter, if the text is longer than 130 characters (I believe that's the limit?), twitlonger could be used.
