### ISSUE TITLE
Add option to select different uploading services for different filetypes

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#11]
You might want to upload text to pastie, images to Imgur and everything else to Google Drive so there should be the option to choose which service you use for what.

**Comment by dtext** [comment]
Implementing seperate config options for each type of media (and documenting them) should be fairly straightforward.

**Comment by dtext** [comment]
@denniseffing' s and my suggestion from #34

> [...] For now, I would just separate the config options, so we have `<mediatype>_provider`.
> 
> [...] We could just read the provider setting for the media type from the config and call its `upload_<mediatype>()` function. If we get an `AttributeError` or `NotImplementedError`, we let the user know that they need to change their config accordingly.
> Internally, all the different functions could just call the `same _upload()` function, or do some adjustments beforehand or afterwards.

for mediatype in ["screenshot", "audio", "file", "text", "video"]
