### ISSUE TITLE
Work out a concept for OAuth

### ISSUE THREAD

**Issue by dtext** [instantshare/instantshare#14]
As everyone uses OAuth now, we need to work out a concept that fulfills the following requirements:
- provides a simple OAuth flow for the user
- is more or less secure from our standpoint (so malicious software can not impersonate our app)
- can be used with most (preferably all) of the storage providers

The main problem is that the client/app secret needs to be kept secret, and to my understanding, the only way to achieve this on a client's machine without tying the secret to a user account and encrypting it is security through obscurity.

The implicit flow may be a way to start here. There are already some experiments with that here: 329bd26d616bcb93d49e11b59074185ca3364250.

**Comment by denniseffing** [comment]
This might be helpful to replace our own OAuth client implementation: https://github.com/requests/requests-oauthlib

**Comment by dtext** [comment]
_oauthlib_ may be more mature and more actively developed. We should evaluate both libraries with regards to our use case.

See:
[https://pypi.python.org/pypi/oauthlib](url)
[https://github.com/idan/oauthlib](url)

**Comment by dtext** [comment]
As 329bd26d616bcb93d49e11b59074185ca3364250 is merged now, we might also consider to call it good for now and revisit the issue in the future.
Personally, I don't see why we couldn't release 0.1 with the current solution in place.

Edit: It seems like the implicit flow is the best we are going to get using OAuth. This is why I'd call this done.

**Comment by denniseffing** [comment]
Agreed. OAuth has its flaws when it comes to open source desktop applications anyways, so I think this is as good as it gets.

**Comment by dtext** [comment]
Alright. Closing this for now.
