### ISSUE TITLE
Add global hotkeys to access functionality in tray mode

### ISSUE THREAD

**Issue by denniseffing** [instantshare/instantshare#17]

**Comment by dtext** [comment]
I don't really see this being a Windows only feature, as people might want it on Linux as well.
But first, we would need to port the tray mode (or rewrite it using a platform-agnostic library).

For the time being though, linking hotkeys to commands is very easy on linux, and with #18 resolved (or even now), we would be able to get the same features that are added for windows in #25.

**Comment by denniseffing** [comment]
I completely agree. I omitted Linux on purpose since you can use the CLI for now. 
We can think about adding this for Linux after we implement the Linux variant of the tray icon.

**Comment by denniseffing** [comment]
Closing this for now, since you can easily map hotkeys to the CLI of instantshare in Linux.
We might revisit this issue when (or if) we implement the tray mode for Linux.
