### ISSUE TITLE
Create CLI

### ISSUE THREAD

**Issue by dtext** [instantshare/instantshare#18]
We should look into creating a command line interface similar to git:

`instantshare screen` to take a screenshot with default settings
`instantshare screen --whole` to take a screenshot of the whole screen
`instantshare text` to share text from the clipboard
...

These functions should be seperated into distinct modules.

**Comment by denniseffing** [comment]
This might be helpful: 
https://github.com/rdegges/skele-cli

**Comment by dtext** [comment]
We could also learn from [docker-compose](https://github.com/docker/compose) when it comes to CLI features. I am currently working on this, and compose has been a very good inspiration.

What they are doing with their main entrypoint is very interesting: The file [bin/docker-compose](https://github.com/docker/compose/blob/master/bin/docker-compose) only imports and executes the package. On Linux, it can be added to the PATH (or copied to a location like `/usr/bin` to begin with) and then executed by typing `docker-compose`. On Windows, that python file could be compiled to an exe using PyInstaller. If that is added to the PATH, it can be executed in the same way.

Would this be interesting? I am also looking at issue #12 here.

Edit: I will be moving this to a new issue when #29 is merged.
