### ISSUE TITLE
Integrate persistent data encryption

### ISSUE THREAD

**Issue by dtext** [instantshare/instantshare#22]
We want to be able to encrypt persistent data like access tokens or credentials.

In pull request #21, encryption was already implemented. We just need to integrate it, considering the following use cases:

- [x] Enter password everytime instantshare runs, maximum security. For entering the password, we would need a little popup window, this can be done in QT (pyqt), GTK (pygtk) or TK (tkinter).
- [X] Use the system keyring to store the password for encryption. The keyring can be implemented using the cross platform [keyring](https://pypi.python.org/pypi/keyring) package.
- [X] This should be configurable in the config file

Edit: Updated task list

**Comment by dtext** [comment]
I got started on this, however I don't really want to find myself creating GUIs. So I will do the keyring integration first. The user will be asked for the password on the command line for now, which is only a feasible option if keyring usage is enabled (run once from command line, enter password, don't worry about it again).

This is the case because instantshare will usually run in the background, so we really need a GUI for password dialogues.

**Comment by dtext** [comment]
I made a very basic (read: ugly) GUI for this. See #43

**Comment by denniseffing** [comment]
Since everything is working now (on feature branches), I think this can be closed. Reopen it if you think something is missing.
