### ISSUE TITLE
Implement ability to cancel taking a cropped screenshot

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#24]
For example using the <kbd>Esc</kbd> key

**Comment by dtext** [comment]
Gnome Screenshot cancels the screenshot when pressing <kbd>Esc</kbd>, but the upload code is still called. It fails with an exception though because the screenshot file does not exist. Not the cleanest solution, I'm all for integrating this properly.

**Comment by denniseffing** [comment]
Okay so this issue depends on the specified screenshot tool (i.e. windows_tk or gnome_screenshot) and on the error handling after canceling.

TK: We should be able to bind a key listener function to the TK canvas like this:

``` python
def cancel(key):
    root.destroy()

can.bind("<KeyPress>", cancel)
```

gnome screenshot: Any ideas?
