### ISSUE TITLE
Rework dependency management to support dependencies for different platforms

### ISSUE THREAD

**Issue by denniseffing** [instantshare/instantshare#26]
As of now, we use the requirements.txt to describe the dependencies needed. This approach doesn't allow us to seperate the dependencies needed for different platforms.

**Comment by dtext** [comment]
Adding this issue to the version 0.1 milestone because #27 depends on this.

**Comment by dtext** [comment]
~~I think [this](https://www.python.org/dev/peps/pep-0496/) should be the solution of choice for `requirements.txt` as well as `setup.py`.~~

Edit: That PEP is currently a draft.
