### ISSUE TITLE
Record and upload sound

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#4]
It would be cool to be able to share little audio snippets.

Considerations:
- microphone recordings
- recording of the computer for music sharing, ....
- how to switch between these two

**Comment by dtext** [comment]
I found the [sounddevice](https://pypi.python.org/pypi/sounddevice) package, which might make this task quite easy. Maybe we can add this to 0.2?

**Comment by dtext** [comment]
There is also this [gist](https://gist.github.com/3demax/4653037) by 3demax for recording opus, which seems even more appealing to me.

**Comment by dtext** [comment]
Regarding the considerations:

I don't know of a simple way to switch between two audio devices. There is pull request #34, but that only implements recording from the attached microphone.

PyAudio's input stream, by default, uses the standard audio device. I don't know of a simple way to switch devices. Even if I did, they can all have different names, and I'd imagine there needs to be some kind of interface to the platform's sound device implementation.

And this is just for existing devices. For recording from standard output device, we would need to do some mixing, which could be very complex (without having looked to deep into it). All that for the added benefit of being able to record and share sound you are already playing. I'm not even sure if that is a sensible use case for a tool like instantshare.

**Comment by florianluediger** [comment]
I agree on the fact that there is not much use for sharing audio which is being played by your computer and there certainly would be a lot of effort needed to make this work.
I would suppose to reduce the goals of this issue to only be able to record audio from the microphone, which is already being addressed in pull request #34. (at least for the assigned milestone "Version 0.2")
