### ISSUE TITLE
Merge ownCloud support as soon as pyocclient is updated

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#6]
The Owncloud API does not seem to support Python 3.5 just yet so implement this feature whenever the API gets updated.

**Comment by dtext** [comment]
Rebased the old feature branch: 7859b41b26e925573a5356e50918185e619c651c

This should be functional as soon as pyocclient 0.3 comes out. Track the progress here:
https://github.com/owncloud/pyocclient/milestone/2
