### ISSUE TITLE
Imgur: Implement uploading images to a particular user account.

### ISSUE THREAD

**Issue by florianluediger** [instantshare/instantshare#8]
Implement the upload of screenshots to the popular platform Imgur.

**Comment by denniseffing** [comment]
Imgur has three different options when registering an application for API usage:
1. OAuth authorization with a callback URL
2. ~~OAuth authorization without a callback URL~~
3. Anonymous usage without user authorization

_2 is definitely not an option, we need the callback URL (redirect URI) for our OAuth2 client._

~~It seems like we have to decide whether we want to use user authorization or anonymous usage, we can't have both. Any thoughts?~~

Edit: It might be possible to use both, even though you specified OAuth2 authorization with a callback URL in your Imgur application settings. ~~Needs further testing.~~

Imgur Instantshare Client ID: a5e814c239e21f0

Edit2: There is no option to change the authorization option after creating the app on Imgur (wow...). I created the app with the anonymous usage option with callback URL `http://localhost:4795/`

Edit3: Just went through some tests, OAuth authorization works fine.

**Comment by denniseffing** [comment]
Providing a client secret seems to be necessary to retrieve a new access token from a refresh token.
See https://api.imgur.com/oauth2

I opened a thread in the official Imgur community forum asking for another way to obtain an access token from a refresh token without providing the client secret.

https://community.imgur.com/t/obtain-new-access-token-from-refresh-token-without-client-secret/27346

Edit: According to the answers in the community forum, there is no way to obtain a new access token from a refresh token without providing the client secret. The only way to upload images to a particular account is to force the user to re-authorize after 28 days (default expiration period of Imgur).

**Comment by dtext** [comment]
I honestly don't think that that is a big problem. 28 days is a reasonable amount of time, and considering that the technical limitations imposed by imgur are responsible for this, we should not worry about it.
After all, reauthentication can be performed by the user with the click of a button. We just need to handle the expiration of the access token correctly and everything should be fine.
